{
 "title": "Crowdsec",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Descisions Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_active_decisions)" }
   ]
  },
  {
   "title": "Alerts Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_alerts)" }
   ]
  },
  {
   "title": "Decisions per Scenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Alerts per Scenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "cs_alerts{}", "legendFormat": "{{reason}}" }
   ]
  }
 ]
}