services:
    archivebox:
#        network_mode: container:vpn
        container_name: archivebox
        image: archivebox/archivebox:latest
        command: server --quick-init 0.0.0.0:9753
        volumes:
            - ${DOCKER_DATA}/webarchive/data:/data
        environment:
            - REVERSE_PROXY_USER_HEADER=Gap-Auth
            - REVERSE_PROXY_WHITELIST=172.20.0.0/24
            - ALLOWED_HOSTS=archive.${DOMAIN}                   # set this to the hostname(s) you're going to serve the site from!
            - CSRF_TRUSTED_ORIGINS=https://archive.${DOMAIN}  # you MUST set this to the server's URL for admin login and the REST API to work
            - SAVE_ARCHIVE_DOT_ORG=False
            - SAVE_FAVICON=False
            - CHROME_BINARY=chromium-browser
            - PUBLIC_INDEX=False                 # set to False to prevent anonymous users from viewing snapshot list
            - PUBLIC_SNAPSHOTS=False             # set to False to prevent anonymous users from viewing snapshot content
            - PUBLIC_ADD_VIEW=False             # set to True to allow anonymous users to submit new URLs to archive
            - PUID=1000                        # set to your host user's UID & GID if you encounter permissions issues
            - PGID=1000                        # UID/GIDs lower than 500 may clash with system uids and are not recommended
            # - USER_AGENT="..."                # set a custom USER_AGENT to avoid being blocked as a bot
            # For more info, see: https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#configuration
        labels:
            - traefik.enable=true
            - traefik.http.routers.archivebox.rule=Host(`archive.${DOMAIN}`)
            - traefik.http.services.archivebox.loadbalancer.server.port=9753
            - traefik.http.routers.archivebox.middlewares=sso-required@file


    ### Example: Run PYWB in parallel and auto-import WARCs from ArchiveBox

    pywb:
        container_name: pywb
        image: webrecorder/pywb:2.9.0
        entrypoint: /bin/sh -c '(wb-manager init default || test $$? -eq 2) && wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback;'
        environment:
            - INIT_COLLECTION=archivebox
        ports:
            - ${IP}:8686:8080
        volumes:
            - ${DOCKER_DATA}/webarchive/data:/archivebox
            - ${DOCKER_DATA}/webarchive/wayback:/webarchive