services:
    jupyter:
        container_name: jupyter
        image: jupyter/minimal-notebook
        restart: unless-stopped
        volumes:
            - ./notebooks:/home/jovyan/notebooks:rw
#            - ./jupyter_server_config.json:/home/jovyan/.jupyter/jupyter_server_config.json
        labels:
            - traefik.enable=true
            - traefik.http.routers.jupyter.rule=Host(`jupyter.${DOMAIN}`)
            - traefik.http.services.jupyter.loadbalancer.server.port=8888
            - traefik.http.routers.jupyter.middlewares=sso-required@file