apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1
  - name: loki
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://grafana-prometheus:9090
    password:
    user:
    database:
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar
    withCredentials:
    isDefault:
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true
  - name: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://grafana-loki:3100
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true