global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 10s
    external_labels:
        monitor: 'Alertmanager'

rule_files:
    - 'alert.rules'

scrape_configs:
    - job_name: 'speedtest-psychevps'
      metrics_path: /metrics
      scrape_interval: 59m
      scrape_timeout: 60s
      static_configs:
          - targets: ['grafana-speedtest:9798']

#    - job_name: 'ping'
#      metrics_path: /probe
#      scrape_interval: 15m
#      scrape_timeout: 60s
#      params:
#          module: [http_2xx]  # Look for a HTTP 200 response.
#      file_sd_configs:
#        - files:
#            - pinghosts.yaml
#      relabel_configs:
#          - source_labels: [__address__]
#            regex: '(.*);(.*)'  # first is the url, thus unique for instance
#            target_label: instance
#            replacement: $1
#          - source_labels: [__address__]
#            regex: '(.*);(.*)'  # second is humanname to use in charts
#            target_label: humanname
#            replacement: $2
#          - source_labels: [instance]
#            target_label: __param_target
#          - target_label: __address__
#            replacement: grafana-ping:9115  # The blackbox exporter's real hostname:port.

    - job_name: 'endlessh'
      scrape_interval: 60s
      static_configs:
          - targets: ['grafana-endlessh:2112']

    - job_name: 'crowdsec'
      scrape_interval: 60s
      static_configs:
          - targets: ['crowdsec:6060']

#    - job_name: 'system-stats'
#      scrape_interval: 60s
#      static_configs:
#          - targets: ['127.0.0.1:9100']